In [4]:
import networkx as nx
import numpy as np

def nodes_connected(u, v):
    return u in G.neighbors(v)


def generalisedAdjMatrix(G,x):
    nodelist = nx.nodes(G)
    nsize = len(nodelist)
    mp = np.zeros(shape=(nsize,nsize))
    i = 1
    for n in nodelist:
        c = 0
        for m in nodelist[i:]:
            if(nodes_connected(n,m)):
                mp[n-1,m-1]= mp[m-1,n-1]= 1
            else:
                s = nx.shortest_path_length(G, source=n,target=m)
                mp[n-1,m-1]= mp[m-1,n-1]= (s*pow(x,(s-1)))
        i = i+1
    return mp

In [5]:
import networkx as nx
import numpy as np

def laplacian_energy2(G):
    d_deg = (G.degree()).values()
    deg_sqr = np.sum([deg ** 2 for deg in d_deg])
    deg_sum = 2*len(G.edges())
    Lap_energy = deg_sqr + deg_sum
    return Lap_energy


G = nx.Graph()
edge_list = [(1,2),(2,3),(2,5),(3,4),(4,5)]
G.add_edges_from(edge_list)
laplacian_energy2(G)

32

In [6]:
def generalisedLaplacianEnergy(G,x):
    nodelist = nx.nodes(G)
    nsize = len(nodelist)
    deg_dict = []
    for n in nodelist:
        d = 0
        for m in nodelist[i:]:
            if(nodes_connected(n,m)):
                d = d+1
            else:
                s = nx.shortest_path_length(G, source=n,target=m)
                d = d + (s*pow(x,(s-1)))
        deg_dict[n] = d
    return deg_dict

G = nx.Graph()
edge_list = [(1,2),(2,3),(2,5),(3,4),(4,5)]
G.add_edges_from(edge_list)
generalisedLaplacianEnergy(G, 0.4)

NameError: name 'i' is not defined

In [7]:
def generalisedLaplacianMatrix(G,x):
    nodelist = nx.nodes(G)
    nsize = len(nodelist)
    mp = np.zeros(shape=(nsize,nsize))
    i = 1
    for n in nodelist:
        c = 0
        for m in nodelist[i:]:
            if(nodes_connected(n,m)):
                mp[n-1,m-1]= mp[m-1,n-1]= -1
            else:
                s = nx.shortest_path_length(G, source=n,target=m)
                mp[n-1,m-1]= mp[m-1,n-1]= -(s*pow(x,(s-1)))
        i = i+1
        mp[n-1,n-1]= np.sum(mp[n-1]*-1)
    return mp

In [15]:
G = nx.Graph()
edge_list = [(1,2),(2,3),(2,5),(3,4),(4,5)]
G.add_edges_from(edge_list)
m = generalisedAdjMatrix(G,0.4)
print(m)

[[ 0.    1.    0.8   0.48  0.8 ]
 [ 1.    0.    1.    0.8   1.  ]
 [ 0.8   1.    0.    1.    0.8 ]
 [ 0.48  0.8   1.    0.    1.  ]
 [ 0.8   1.    0.8   1.    0.  ]]


In [18]:
mm = generalisedLaplacianMatrix(G,0.4)
print(mm)

[[ 3.08 -1.   -0.8  -0.48 -0.8 ]
 [-1.    3.8  -1.   -0.8  -1.  ]
 [-0.8  -1.    3.6  -1.   -0.8 ]
 [-0.48 -0.8  -1.    3.28 -1.  ]
 [-0.8  -1.   -0.8  -1.    3.6 ]]


In [33]:
import networkx as nx

G = nx.Graph()
edge_list = [(1,2),(1,3),(2,3),(3,4),(3,5),(5,6)]
G.add_edges_from(edge_list)
nx.adjacency_spectrum(G)

array([ 2.37987812+0.j, -1.92022087+0.j,  1.00000000+0.j,  0.29136689+0.j,
       -1.00000000+0.j, -0.75102414+0.j])

In [34]:
import numpy.linalg as nl

M = generalisedAdjMatrix(G,0.23)
nl.linalg.eig(M)

(array([ 3.23280781,  0.45984847, -0.28980582, -1.37020707, -1.        ,
        -1.03264339]),
 array([[ -4.16550127e-01,  -3.51458940e-01,  -3.75449329e-01,
           1.95209902e-01,   7.07106781e-01,   1.54575224e-01],
        [ -4.16550127e-01,  -3.51458940e-01,  -3.75449329e-01,
           1.95209902e-01,  -7.07106781e-01,   1.54575224e-01],
        [ -5.33637587e-01,  -7.98098345e-02,   1.49760709e-01,
          -7.85334234e-01,  -7.36658424e-16,  -2.63975730e-01],
        [ -3.55637922e-01,  -1.45133840e-01,   8.15793747e-01,
           3.11022393e-01,   4.23717381e-16,   3.00338928e-01],
        [ -4.15513395e-01,   4.91272091e-01,  -2.96240944e-02,
           4.37645838e-01,   1.60524704e-16,  -6.27366627e-01],
        [ -2.62817799e-01,   6.95824344e-01,  -1.71027215e-01,
          -1.36994598e-01,   1.52824412e-16,   6.31456616e-01]]))

In [17]:
import networkx as nx

G = nx.Graph()
edge_list = [(1,2),(1,3),(1,4)]
G.add_edges_from(edge_list)
nx.laplacian_spectrum(G)

array([  1.11022302e-16,   1.00000000e+00,   1.00000000e+00,
         4.00000000e+00])

In [20]:
import numpy.linalg as nl

M = generalisedLaplacianMatrix(G,0.31)
nl.linalg.eig(M)

(array([  4.00000000e+00,   1.11022302e-16,   2.86000000e+00,
          2.86000000e+00]),
 array([[  8.66025404e-01,  -5.00000000e-01,  -8.95709721e-17,
           2.17241517e-17],
        [ -2.88675135e-01,  -5.00000000e-01,   8.16496581e-01,
          -1.98029509e-01],
        [ -2.88675135e-01,  -5.00000000e-01,  -4.08248290e-01,
          -5.86979586e-01],
        [ -2.88675135e-01,  -5.00000000e-01,  -4.08248290e-01,
           7.85009095e-01]]))